### PR TITLE
chore: update calls to createClassNameProp to better use the params form

### PR DESCRIPTION
**Pull request by josh-degraw**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

This just updates anywhere that was calling `createClassNameProp` to pass variadic args instead of concatenating a string inline, to improve readability.

### CODE REVIEW

**Comment by josh-degraw** [comment]
https://codesandbox.io/s/ps-react-typescript-cll7g3?file=/src/App.tsx

**Comment by caseybaggz** [comment]
> https://codesandbox.io/s/ps-react-typescript-cll7g3?file=/src/App.tsx

This just looks like a default sandbox on my side? Did you click save on the App file before clicking the share link? 🤷‍♀️

**Comment by josh-degraw** [comment]
> > https://codesandbox.io/s/ps-react-typescript-cll7g3?file=/src/App.tsx
> 
> This just looks like a default sandbox on my side? Did you click save on the App file before clicking the share link? 🤷‍♀️ 

What are you expecting to be there?

**Comment by caseybaggz** [comment]
> > > https://codesandbox.io/s/ps-react-typescript-cll7g3?file=/src/App.tsx
> > 
> > 
> > This just looks like a default sandbox on my side? Did you click save on the App file before clicking the share link? 🤷‍♀️
> 
> What are you expecting to be there?

Some APIs being used. The sandbox builds packages based off this PR, so just validation that they still work fine. You don't have to do that much. Just a few on the APIs you updated for easy validation that we aren't shipping recursive visual bugs.

**Comment by josh-degraw** [comment]
Like this? https://codesandbox.io/s/ps-react-typescript-forked-wwd29d?file=/src/App.tsx

**Comment by caseybaggz** [comment]
> Like this? https://codesandbox.io/s/ps-react-typescript-forked-wwd29d?file=/src/App.tsx

Perfectly splendid! And, in the future, you can just click the "x" on any PS libs you aren't testing so the sandbox loads a little faster. 😉

**Review by caseybaggz — APPROVED** [review]

**Pull request merged**
