### PR TITLE
Utilize TS `satisfies` and generic to improve generated style type definitions

### PR DESCRIPTION
**Pull request by josh-degraw**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Generated styles are currently a "black box", with no type information about things such as if a nested selector exists (e.g. '&:hover'). To fully interoperate in a custom solution using the generated styles, one often needs to know which of these nested selectors may be available.

## What is the new behavior?

This PR utilizes `satisfies` from TypeScript 4.9 to improve typings for generated style objects. The effect is similar to using `as const` but doesn't require consuming code to be readonly, among some other benefits. The end result of this means that both using generated styles directly and using the result of `createJSProps` will include nested selectors in the generated type definition to aid in discoverability and correctness.

## Other information

The functionality and type-correctness of these changes seem to work exactly as I'd expect. However, currently as the project is configured (at least on my machine), Jest isn't able to parse the `satisfies` keyword so I can't validate the tests yet. I've tried several things to try and get jest to parse it correctly with no success. I've tried reproducing the problem, but if I just make a minimal repo with `jest`, `babel-jest`, `typescript@4.9` like what's in this repo, and if I pin `@babel/core` to version `^7.20.12` it works without any issues, so there's something about this repo's environment that either I'm just not understanding or unaware of.

### CODE REVIEW

**Comment by caseybaggz** [comment]
@josh-degraw we finally have the Codesandbox PR issue resolved on `main` so if you update the latest, you will get a PR sandbox link to test of the current state of this branch!

**Comment by josh-degraw** [comment]
Still working on seeing if I can figure out why it wouldn't be working here. But I did make a [minimal repro](https://github.com/josh-degraw/babel-ts-jest-test) to demonstrate that it can work with PnP. There's gotta be something about the config for the repo that I'm just not understanding. It's looking like it might be more related to babel than jest, since the build itself seems to be failing now. My current hunch is it's something to do with mismatched dependency versions with the monorepo setup, but that's just a working theory, I don't have much to confirm that yet. I've been tweaking dependencies etc. all over the place and so far nada

**Comment by caseybaggz** [comment]
> Still working on seeing if I can figure out why it wouldn't be working here. But I did make a [minimal repro](https://github.com/josh-degraw/babel-ts-jest-test) to demonstrate that it can work with PnP. There's gotta be something about the config for the repo that I'm just not understanding. It's looking like it might be more related to babel than jest, since the build itself seems to be failing now. My current hunch is it's something to do with mismatched dependency versions with the monorepo setup, but that's just a working theory, I don't have much to confirm that yet. I've been tweaking dependencies etc. all over the place and so far nada.
> 
> (only marked this as ready for review to try and see sandbox etc. but I'm not seeing anything about that yet, though I guess that probably wouldn't work if the build fails lol)

Yeah, the Required checks have to pass, but you also might need to update your fork. If it is a dependency issue, let's try and prevent the code impact from increasing out of the single feature for this PR and create another PR to address that. This year we want to really hone in on perfecting the "single issue PR" goal. 👍

**Comment by Rykus0** [comment]
I found [this issue](https://github.com/babel/babel/issues/15157).  This morning I can try some of their suggestions to see if they help at all.

**Comment by josh-degraw** [comment]
> An upgrade of all `@babel/*` dependencies across the board resolves the `satisfies` issue.

SMH I swear I tried that like 700 different ways 🤦🏻‍♂️. Could you at least push up those version updates here so I can test those changes on my branch as well? 

FWIW I think it might help in the future to not pin `latest` directly in the `package.json` files so it's more clear what the versions used actually are and make updating dependencies more straightforward.

**Comment by josh-degraw** [comment]
The builds finally pass, thank you so much! How did you get the babel issues to resolve? I swear I thought I tried everything, `yarn up @babel/*`, I added `resolutions`, etc. What did you end up doing that actually fixed the dependency issues?

**Comment by josh-degraw** [comment]
[Sandbox Link](https://codesandbox.io/s/satisfies-sandbox-8z9zbz?file=/src/App.tsx) (the types don't complain at me anymore 🎉)

**Review by caseybaggz — DISMISSED** [review]
@josh-degraw @Rykus0 In the future, if there are dep updates that are involved, let's please try and keep those in a separate PR to make it easier to adjust if for some reason we ever need to in the commits.

We definitely lack that as a team and I don't want this pattern to become too normal as we start scaling this year. 👍

**Comment by Rykus0** [comment]
> The builds finally pass, thank you so much! How did you get the babel issues to resolve? I swear I thought I tried everything, `yarn up @babel/*`, I added `resolutions`, etc. What did you end up doing that actually fixed the dependency issues?

It was `yarn up -R "@babel/*"` that did it

**Comment by Rykus0** [comment]
> I found something that works for the types. Just need to see if I can clean it up.

@josh-degraw FYI - #1076 Should negate the need for the changes I made here in terms of the type complexity (buttonJS and menuJS)

**Review by Rykus0 — APPROVED** [review]

**Review by caseybaggz — APPROVED** [review]

**Pull request merged**
